from selenium.webdriver.common.by import By

LOGIN_BURGER = (By.XPATH, '//*[contains(@class, "responseHead-module-burger")]')
LOGIN_BUTTON = (By.XPATH, '//*[contains(@class, "responseHead-module-button")]')
LOGIN_INPUT = (By.NAME, 'email')
PASSWORD_INPUT = (By.NAME, 'password')
SIGN_IN_BUTTON = (By.XPATH, '//*[contains(@class, "authForm-module-button")]')
USER_NAME = (By.XPATH, '//*[contains(@class, "right-module-userName")]')
RIGHT_UPPER_BUTTON = (By.CSS_SELECTOR, '[class*=right-module-rightButton]')
LOGOUT_BUTTON = (By.CSS_SELECTOR, '[class*=rightMenu-module-rightMenuItem] [href="/logout"]')
PROFILE_BUTTON = (By.CSS_SELECTOR, '[class*=center-module] [href="/profile"]')
MORE_BUTTON = (By.XPATH, '//*[contains(@class, "center-module-more")]')
BILLING_BUTTON = (By.CSS_SELECTOR, '[class*=center-module] [href="/billing"]')
AUTODEPOSIT_BUTTON = (By.XPATH, '//*[contains(@data-type, "autodeposit")]')
STATISTICS_BUTTON = (By.CSS_SELECTOR, '[class*=center-module] [href="/statistics"]')
REPORTS_BUTTON = (By.XPATH, '//*[contains(@href, "/statistics/reports")]')
NAME_INPUT = (By.XPATH, '//*[contains(@class, "js-contacts-field-name")]//input')
PHONE_INPUT = (By.XPATH, '//*[contains(@class, "js-contacts-field-phone")]//input')
SUBMIT_INFO_BUTTON = (By.XPATH, '//button[contains(@class, "button_submit")]')
INFO_EDIT_RESULT = (By.XPATH, '//*[contains(@class, "notification_success")]/*[contains(@class, "js-notification-content")]')
INVALID_EMAIL_NOTIFICATION = (By.XPATH, '//*[contains(@class, "notify-module-error")]')